"""schema inicial: clientes, perfis, editais, matches, alertas

Revision ID: 6a8d7f3887ef
Revises: 
Create Date: 2026-07-17 19:17:40.569162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a8d7f3887ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('editais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pncp_id', sa.String(length=64), nullable=False),
    sa.Column('orgao', sa.String(length=255), nullable=False),
    sa.Column('objeto', sa.String(), nullable=False),
    sa.Column('esfera', sa.Enum('federal', 'estadual', 'municipal', name='esfera'), nullable=False),
    sa.Column('modalidade', sa.String(length=64), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('municipio', sa.String(length=255), nullable=True),
    sa.Column('valor_estimado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('data_publicacao', sa.Date(), nullable=False),
    sa.Column('link_pncp', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pncp_id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('edital_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['edital_id'], ['editais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'edital_id')
    )
    op.create_table('perfis_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('cnaes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('ufs', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('palavras_chave', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('valor_minimo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_maximo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id')
    )
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.Enum('email', 'whatsapp', name='canalalerta'), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'enviado', 'falhou', name='statusalerta'), nullable=False),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alertas')
    op.drop_table('perfis_cliente')
    op.drop_table('matches')
    op.drop_table('editais')
    op.drop_table('clientes')
    # ### end Alembic commands ###
