"""adiciona email ao cliente

Revision ID: eaa09caf4a2e
Revises: 6a8d7f3887ef
Create Date: 2026-07-17 19:29:53.438823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa09caf4a2e'
down_revision: Union[str, None] = '6a8d7f3887ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('email', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'email')
    # ### end Alembic commands ###
